package com.ronald.elibrary.entity;
// Generated 30/08/2015 11:06:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Autor generated by hbm2java
 */
@Entity
@Table(name="autor"
    ,catalog="elibrary"
)
public class Autor  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private Set<Libro> libros = new HashSet<Libro>(0);

    public Autor() {
    }

	
    public Autor(String nombres, String apellidos) {
        this.nombres = nombres;
        this.apellidos = apellidos;
    }
    public Autor(String nombres, String apellidos, Set<Libro> libros) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.libros = libros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombres", nullable=false, length=245)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false, length=245)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="libro_autor", catalog="elibrary", joinColumns = { 
        @JoinColumn(name="autor_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="libro_id", nullable=false, updatable=false) })
    public Set<Libro> getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set<Libro> libros) {
        this.libros = libros;
    }




}


