package com.ronald.elibrary.entity;
// Generated 30/08/2015 11:06:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Editor generated by hbm2java
 */
@Entity
@Table(name="editor"
    ,catalog="elibrary"
)
public class Editor  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private String email;
     private String usuario;
     private String contrasenha;
     private Set<Libro> libros = new HashSet<Libro>(0);

    public Editor() {
    }

	
    public Editor(String nombres, String email, String usuario, String contrasenha) {
        this.nombres = nombres;
        this.email = email;
        this.usuario = usuario;
        this.contrasenha = contrasenha;
    }
    public Editor(String nombres, String apellidos, String email, String usuario, String contrasenha, Set<Libro> libros) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.usuario = usuario;
       this.contrasenha = contrasenha;
       this.libros = libros;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombres", nullable=false, length=145)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=145)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="usuario", nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasenha", nullable=false, length=45)
    public String getContrasenha() {
        return this.contrasenha;
    }
    
    public void setContrasenha(String contrasenha) {
        this.contrasenha = contrasenha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="editor")
    public Set<Libro> getLibros() {
        return this.libros;
    }
    
    public void setLibros(Set<Libro> libros) {
        this.libros = libros;
    }




}


