package com.ronald.elibrary.entity;
// Generated 30/08/2015 11:06:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,catalog="elibrary"
)
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nombres;
     private String apellidos;
     private String email;
     private String usuario;
     private String contrasenha;
     private Set<Puntuacion> puntuacions = new HashSet<Puntuacion>(0);
     private Set<Comentario> comentarios = new HashSet<Comentario>(0);

    public Usuario() {
    }

	
    public Usuario(String nombres, String email, String usuario, String contrasenha) {
        this.nombres = nombres;
        this.email = email;
        this.usuario = usuario;
        this.contrasenha = contrasenha;
    }
    public Usuario(String nombres, String apellidos, String email, String usuario, String contrasenha, Set<Puntuacion> puntuacions, Set<Comentario> comentarios) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.email = email;
       this.usuario = usuario;
       this.contrasenha = contrasenha;
       this.puntuacions = puntuacions;
       this.comentarios = comentarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombres", nullable=false, length=145)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", length=145)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="email", nullable=false, length=145)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="usuario", nullable=false, length=45)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasenha", nullable=false, length=45)
    public String getContrasenha() {
        return this.contrasenha;
    }
    
    public void setContrasenha(String contrasenha) {
        this.contrasenha = contrasenha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Puntuacion> getPuntuacions() {
        return this.puntuacions;
    }
    
    public void setPuntuacions(Set<Puntuacion> puntuacions) {
        this.puntuacions = puntuacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    public Set<Comentario> getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set<Comentario> comentarios) {
        this.comentarios = comentarios;
    }

    @Override
    public String toString()
    {
        return "Usuario{" + "id=" + id + ", nombres=" + nombres + ", apellidos=" + apellidos + ", email=" + email + ", usuario=" + usuario + ", contrasenha=" + contrasenha + '}';
    }




}


